config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :affiliates
  end
end

app/models/spree/affiliate.rb
module Spree
  class Affiliate < ActiveRecord::Base
    validates_presence_of :name, :link, :display_url
  end
end

app/controllers/spree/admin/affiliates_controller.rb
module Spree
  module Admin
    class AffiliatesController < ResourceController

    end
  end
end

app/views/spree/admin/affiliates/_form.html.erb
<div data-hook='admin_affiliates_form_fields' class='row'>
  <div class='row'>
    <div class='alpha five columns'>
      <div class='field '>
        <%= f.label :name, Spree.t(:name) %>
        <%= f.text_field :name, class: 'fullwidth' %>
      </div>
    </div>

    <div class='five columns'>
      <div class='field '>
        <%= f.label :display_url, Spree.t(:display_url) %>
        <%= f.text_field :display_url, class: 'fullwidth' %>
    </div>
  </div>

  <div class='omega five columns'>
    <div class='field '>
      <%= f.label :link, Spree.t(:link) %>
      <%= f.text_field :link, class: 'fullwidth' %>
    </div>
  </div>
</div>

app/views/spree/admin/affiliates/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:affiliates) %> <i class="icon-arrow-right"></i>
   <%= @affiliate.name %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_affiliates_list), admin_affiliates_path, :class => 'button' %></li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @affiliate } %>

<%= form_for [:admin, @affiliate] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/affiliates/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:affiliates) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_affiliate), new_object_url, :icon => 'icon-plus', :id => 'admin_new_slide_link' %>
  </li>
<% end %>

<% if @affiliates.any? %>
  <table class="index admin_affiliates">
    <colgroup>
      <col style='width: 20%' />
      <col style='width: 30%' />
      <col style='width: 30%' />
      <col style='width: 20%' />
    </colgroup>
    <thead data-hook='admin_affiliates_index_headers'>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:display_url) %></th>
      <th><%= Spree.t(:link) %></th>
      <th class='actions'></th>
    </thead>
    <tbody>
      <% @affiliates.each do |affiliate|%>
        <tr id="<%= dom_id affiliate %>" data-hook='admin_trackers_index_rows'  class="<%= cycle('odd', 'even')%>">
          <td class='align-center'><%= affiliate.name %></td>
          <td class='align-center'><%= affiliate.display_url %></td>
          <td class='align-center'><%= affiliate.link %></td>
          <td class='actions'>
            <%= link_to_edit affiliate, no_text: true %>
            <%= link_to_delete affiliate, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class='alpha twelve columns no-objects-found'>
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/affiliate')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_affiliate_path %>!
  </div>
<% end %>

app/views/spree/admin/affiliates/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_affiliate) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_affiliates_list), admin_affiliates_path, :class => 'button' %></li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @affiliate} %>

<%= form_for [:admin, @affiliate] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>